// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqCSgVefNmdKKolfzzS2lBRdiMWjkDG1Q',
    appId: '1:34116200391:web:c3df3c3a80558d8d6b9be2',
    messagingSenderId: '34116200391',
    projectId: 'food-delivery-bf9dd',
    authDomain: 'food-delivery-bf9dd.firebaseapp.com',
    storageBucket: 'food-delivery-bf9dd.appspot.com',
    measurementId: 'G-KZXZ9YH767',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKldLpxZT5RJBgvYIn1WANszM77vmNtI',
    appId: '1:34116200391:android:af4c3f06ac3bf2eb6b9be2',
    messagingSenderId: '34116200391',
    projectId: 'food-delivery-bf9dd',
    storageBucket: 'food-delivery-bf9dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLvqQKRcsEpOJJ90SBJgOSFgX9-efNfRg',
    appId: '1:34116200391:ios:af94ce9000c282696b9be2',
    messagingSenderId: '34116200391',
    projectId: 'food-delivery-bf9dd',
    storageBucket: 'food-delivery-bf9dd.appspot.com',
    androidClientId: '34116200391-aeedo8o9jqcq86iq6rb9pl9gjskeka9d.apps.googleusercontent.com',
    iosClientId: '34116200391-9ui4i6pfcshrpasoai2bl8ul5hcick4k.apps.googleusercontent.com',
    iosBundleId: 'asia.goldenowl.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLvqQKRcsEpOJJ90SBJgOSFgX9-efNfRg',
    appId: '1:34116200391:ios:af94ce9000c282696b9be2',
    messagingSenderId: '34116200391',
    projectId: 'food-delivery-bf9dd',
    storageBucket: 'food-delivery-bf9dd.appspot.com',
    androidClientId: '34116200391-aeedo8o9jqcq86iq6rb9pl9gjskeka9d.apps.googleusercontent.com',
    iosClientId: '34116200391-9ui4i6pfcshrpasoai2bl8ul5hcick4k.apps.googleusercontent.com',
    iosBundleId: 'asia.goldenowl.foodDelivery',
  );
}
